### PR TITLE
fix: delay before using policy

### PR DESCRIPTION
**Pull request by shemau**
### Description

Issue: 7308

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Upgrades from earlier to version to this version may show a time_sleep.wait_for_authorization_policy being deleted if they are skipping authorisation policy creation. This is expected, since there is no need to delay if the authorisation policy already exists.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
The destroy error is here: https://github.com/terraform-ibm-modules/terraform-ibm-cos/actions/runs/7643532125/job/20825912071#step:7:3586

It is a destroy on the time_sleep for cos_bucket2 which has skip_iam_authorization_policy set to true. So it is never going to create a policy, so it should never have had a delay in the first place.

Since this is the only change breaking the upgrade test, and it only affects the upgrade for this PR, the upgrade tests will be skipped.

**Comment by shemau** [comment]
This failure looks like https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5002.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
