### PR TITLE
fix: update the reference-architectures

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/580

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by SirSpidey — DISMISSED** [review]
Thanks for proactively updating these @Aashiq-J!

Some very small suggestions. One important one is not to use `COS`. Use `Object Storage` or `IBM Cloud Object Storage`.

**Comment by ocofaigh** [comment]
Since Allen is unavailable this week, I'm going to approve and merge this. If any follow up actions, lets get them into a new issue

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
