### PR TITLE
ci: auto mark modules as ready in catalog

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

auto mark modules as ready in catalog now that pipeline supports not publishing during code freeze windows

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by maheshwarishikha** [comment]
@ocofaigh Are we planning to do this for all repositories? If it is so, then we may need to change in pipeline code too.

**Review by maheshwarishikha — APPROVED** [review]

**Comment by ocofaigh** [comment]
@maheshwarishikha Not all repos - for examples, SLZ will still be manual. What pipeline changes are you talking about?

**Comment by maheshwarishikha** [comment]
> @maheshwarishikha Not all repos - for examples, SLZ will still be manual. What pipeline changes are you talking about?

Missed to respond.
I meant, if we are doing it for all repos then validation of `mark_ready` true/false can be removed in pipeline code. But I understand it is not for all repos, so no code change required. Thanks

**Pull request merged**
