### PR TITLE
feat: add role none for resource keys

### PR DESCRIPTION
**Pull request by jor2**
### Description

Support creation of resource key with "NONE" role
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/624

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Support creation of resource key with "NONE" role

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
1.66.0 is now out @jor2

**Review by shemau — DISMISSED** [review]
I am good with the changes in this PR with the exception of common-dev-assets.

I am not sure if this needs to change in this PR, especially given the changes wrt pipelines and rapid cycles on common-dev-assets just at the moment.

**Comment by shemau** [comment]
per #624 and https://github.com/IBM-Cloud/terraform-provider-ibm/commits/v1.66.0/ it should be included.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
