### PR TITLE
fix: update retention policy

### PR DESCRIPTION
**Pull request by iamar7**
### Description

The retention policy of the main module is disabled to prevent from deleting objects from cos bucket.

https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/366

#### Changes that affect the core Terraform module or submodules
- [x] Bug fix
- [ ] New feature
- [ ] Dependency update

#### Changes that don't affect the core Terraform module or submodules
- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other

#### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Through this release the retention is disabled as a default setting and the user must specify explicitly **retention_enabled = true** to enable retention while consuming the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by iamar7** [comment]
Based on the comment [here](https://github.ibm.com/GoldenEye/issues/issues/4576#issuecomment-58904089) I have updated the retention policy for the main module only.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
