### PR TITLE
fix: change the variable name to skip_cos_sm_auth_policy in instance DA

### PR DESCRIPTION
**Pull request by Soaib024**
### Description
https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/700

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

- Changed the varible name to `skip_cos_sm_auth_policy` from `skip_cos_kms_auth_policy`
- Changed the resource name from `ibm_iam_authorization_policy.policy` to `ibm_iam_authorization_policy.secrets_manager_key_manager` to make it consistent with elastic-search
- Added moved block to avoid breaking change
- Added `ibm_iam_authorization_policy.secrets_manager_key_manager.description`

Your notes help the merger write the commit message for the PR that is published in the release notes for the module. --->

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — APPROVED** [review]
The code changes are good and complete.

My only concern is that I do not understand what changing an input parameter in a DA has for DA upgrades. For example a DA upgrading from 8.10.4 (or earlier) to this release has to know to use the old value as the new input. Or are consumers expected to run a `plan` and fix any unexpected changes?

**Comment by Soaib024** [comment]
> The code changes are good and complete.
> 
> My only concern is that I do not understand what changing an input parameter in a DA has for DA upgrades. For example a DA upgrading from 8.10.4 (or earlier) to this release has to know to use the old value as the new input. Or are consumers expected to run a `plan` and fix any unexpected changes?

@daniel-butler-irl @rajatagarwal-ibm

**Comment by ocofaigh** [comment]
@Soaib024 It seems we introduced a regression in this PR. See https://github.com/terraform-ibm-modules/terraform-ibm-cos/issues/708

**Pull request merged**
