### PR TITLE
Examples code updated with changes as requested (default values removed, use of variables restricted to only least, local values used wherever applicable, provider with lowest and one latest version defined, test/plan/apply verified)

### PR DESCRIPTION
**Pull request by marifse**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by marifse** [comment]
@ocofaigh , i have closed that pull request [521](https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/521/files) and created this new one with same changes and also had checked running the tests locally, screenshot is attached here below. Thank you for your help. I will be now working on other modules.

image

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Since you made `cross_region_location` a required variable in the advanced example, you will now need to explictially pass a value for it in the tests that runs it (`TestRunAdvancedExample` and `TestRunUpgradeExample`). 

The problem is both of those tests are using the shared `setupOptions` function to set variables, so if you were to pass the variable in that function, it would break other tests. 

I think the easiest thing to do here is to actually remove to variable `cross_region_location` from the example, and just hard code it [here](https://github.com/marifse/terraform-ibm-cos/blob/2dfabf6b4abaaad95c64fdc464fa4dc2a16b2226/examples/advanced/main.tf#L211) to:
```
cross_region_location = "us" # Supported values are 'us', 'eu', and 'ap'
```

**Comment by marifse** [comment]
> ation = "us" # Supp

@ocofaigh yes i did it. can you please check now, or let me know how i can run the pipeline locally.

> Since you made `cross_region_location` a required variable in the advanced example, you will now need to explictially pass a value for it in the tests that runs it (`TestRunAdvancedExample` and `TestRunUpgradeExample`).
> 
> The problem is both of those tests are using the shared `setupOptions` function to set variables, so if you were to pass the variable in that function, it would break other tests.
> 
> I think the easiest thing to do here is to actually remove to variable `cross_region_location` from the example, and just hard code it [here](https://github.com/marifse/terraform-ibm-cos/blob/2dfabf6b4abaaad95c64fdc464fa4dc2a16b2226/examples/advanced/main.tf#L211) to:
> 
> ```
> cross_region_location = "us" # Supported values are 'us', 'eu', and 'ap'
> ```

@ocofaigh done. hard coded the value for cross region replication.

**Comment by ocofaigh** [comment]
@marifse You must not have your local dev set up correct as pre-commit hooks are failing in pipeline with:
```
Terraform validate with tflint..........................................................Failed
- hook id: terraform_tflint
- exit code: 2

Command 'tflint --init' successfully done:




TFLint in examples/advanced/:
1 issue(s) found:

Warning: [Fixable] variable "cross_region_location" is declared but not used (terraform_unused_declarations)

  on variables.tf line 35:
  35: variable "cross_region_location" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_unused_declarations.md
```

**Comment by marifse** [comment]
sorry my bad i did not run the test after removing the value, have run the test and removed the variable. Can you please check. And also help me how can i run the pipeline locally instead of running it on pull request by commenting /run pipeline.

Thanks, appreciated your help

**Comment by ocofaigh** [comment]
@marifse tests can be run following the steps at https://terraform-ibm-modules.github.io/documentation/#/tests?id=running-the-tests

PR looks good now, can you please resolve conflicts?

**Comment by marifse** [comment]
> @marifse tests can be run following the steps at https://terraform-ibm-modules.github.io/documentation/#/tests?id=running-the-tests
> 
> PR looks good now, can you please resolve conflicts?

@ocofaigh can you pease check now.

**Comment by marifse** [comment]
> @marifse tests can be run following the steps at https://terraform-ibm-modules.github.io/documentation/#/tests?id=running-the-tests
> 
> PR looks good now, can you please resolve conflicts?

@ocofaigh can you pease check now.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
