### PR TITLE
fix: update variable name

### PR DESCRIPTION
**Pull request by maheshwarishikha**
### Description

Updates the variable from `encryption_enabled` to `kms_encryption_enabled`.

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [x] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Change in module interface. Updates the variable name from `encryption_enabled` to `kms_encryption_enabled`. 

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Comment by maheshwarishikha** [comment]
PR changes a variable name which is considered to be a breaking change.
But as per the slack conversation (https://ibm-cloudplatform.slack.com/archives/GG06FQ31P/p1682520629184989) - it seems to be a minor change.

Kindly review.

**Review by shemau — DISMISSED** [review]
LGTM. I think additional specifics about the change should be included in the `release notes contents` section of the PR when it is raised. To make sure the merger is aware that any consumer using this property will need to change it. This is really useful information in the release notes to end users.

**Comment by vburckhardt** [comment]
Just a few conflict with main to resolve and we're good to go

**Review by jojustin — APPROVED** [review]
This has been already approved.  Approving for the conflict resoluation.

**Pull request merged**
