### PR TITLE
fix: tidy up un-required inputs to fscloud module

### PR DESCRIPTION
**Pull request by shemau**
### Description

Remove two un-required variables from fscloud module. These are not used.

#488 

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@shemau I think you misunderstood the issue. The issue says the variable descriptions should be updated. The variables themselves are perfectly valid, but they are optionally, where as the descriptions say they are required which is not true

**Comment by shemau** [comment]
I have reviewed the code again.

Firstly wrt the removing the two variables from the fscloud module. This looks to be a good action. The variable description `Only required if 'create\_cos\_bucket' is true.` is accurate. However, the only time the two variables are used is on a call where the value is hard coded to false. So either they are not passed, or IF they are passed, they are passed through and then not used. So the whole variable is not required and it can be safely removed.

The user can still opt in, it is just not with these two values. Instead the fscloud module uses bucket_config passed to the buckets submodule. The buckets individually carry information for AT and monitoring which can be different by bucket. Having rethought this, that is two other issues:
A. The fscloud example potentially creates a sysdig and does not pass it via a bucket. I think this means it is never used. If we are creating one, it should be used as part of the example, so I will work on that.
B. If the fscloud requirement is to mandate the use of AT and sysdig on all buckets, then it fails; since the user still has full control over this feature. We could increase the validation in the fscloud module to require CRNs for `metrics_monitoring.metrics_monitoring_crn` and for `activity_tracking.activity_tracker_crn`.

**Comment by shemau** [comment]
For A: https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/490/commits/bbf3d82c0584adf869594d7e03d371ae37616f6b passes the cloud monitoring CRN on the bucket. The README.md already said that was monitoring was enabled (but it was not).

For B: https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/490/commits/fcdfd741ef14395ebb1915909bd21440b0106a8e updates the bucket_config specification in the fscloud module so that the activity tracker and cloud monitoring CRNs are required. After discussion, if this is not valid, the commit can be reverted.

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@shemau Thanks for the updates. AT and Sysdig are not FSCloud certified, so they are not required for FSCloud. So please make them optional in the fscloud `bucket_configs` input variable like they were before. All other changes look good.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
